name: personai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  formz: ^0.8.0
  firebase_core: ^4.3.0
  get_it: ^9.2.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
    
  authentication_repository:
    path: packages/authentication_repository

  openai_realtime:
    path: packages/openai_realtime

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
